import {Entity, model, property} from '@loopback/repository';

@model({settings: {strict: false, postgresql: {schema: 'public', table: 'styles'}}})
export class Style extends Entity {
  @property({
    type: 'string',
    required: true,
    postgresql: {
      columnName: 'tenant_id',
      dataType: 'uuid',
    },
  })
  tenant_id: string;

  @property({
    type: 'string',
    id: true,
    generated: true,
    postgresql: {
      columnName: 'id',
      dataType: 'uuid',
    },
  })
  id: string;


  @property({
    type: 'string',
    required: true,
    postgresql: {
      columnName: 'code',
      dataType: 'text',
    },
  })
  code: string;

  @property({
    type: 'string',
    required: true,
    postgresql: {
      columnName: 'name',
      dataType: 'text',
    },
  })
  name: string;

  @property({
    type: 'string',
    required: true,
    postgresql: {
      columnName: 'status',
      dataType: 'text',
    },
  })
  status: string;

  @property({
    type: 'object',
    required: true,
    jsonSchema: {
      // This is where we would put the schema if it were static
    },
    postgresql: {
      columnName: 'data',
      dataType: 'jsonb',
    },
  })
  custom: object;

  @property({
    type: 'date',
    required: false, // Not required in API body
    generated: true, // Generated by the database
    postgresql: {
      columnName: 'created_at',
    },
  })
  created_at: string;

  @property({
    type: 'date',
    required: false, // Not required in API body
    generated: true, // Generated by the database
    postgresql: {
      columnName: 'updated_at',
    },
  })
  updated_at: string;

  constructor(data?: Partial<Style>) {
    super(data);
  }
}

export interface StyleRelations {
  // describe navigational properties here
}

export type StyleWithRelations = Style & StyleRelations;
